[build]
  publish = "dist/spa"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Supabase Edge Functions (if using)
[[edge_functions]]
  function = "create-payment"
  path = "/api/create-payment"

[[edge_functions]]
  function = "verify-payment"
  path = "/api/verify-payment"

# Custom domain configuration
[context.production]
  environment = { VITE_APP_ENV = "production", VITE_APP_URL = "https://famechase.com" }

[context.deploy-preview]
  environment = { VITE_APP_ENV = "preview" }

[context.branch-deploy]
  environment = { VITE_APP_ENV = "development" }

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://test.payu.in https://secure.payu.in; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://test.payu.in https://secure.payu.in; frame-src https://test.payu.in https://secure.payu.in;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
